//------------------------------------------------------------------------
// Copyright(c) 2023 .
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"ChorusEffect.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"ChorusEffect VST3 (64Bit)"
#else
#define stringFileDescription	"ChorusEffect VST3"
#endif
#define stringCompanyName		"\0"
#define stringLegalCopyright	"Copyright(c) 2023 ."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
